docs: Clarify COM819 and formatter interaction (#25045)
When fixing https://github.com/astral-sh/ruff/pull/25044 and review what
other rules might not be documented, I've stumbled upon
https://docs.astral.sh/ruff/rules/prohibited-trailing-comma/ which is
documented, but it seems to be more than just redundant.

Using this rule changes the meaning of using magic comma in some cases.
E.g. `foo = (1, 2, 3,)` - if user would run `ruff check` first, then it
would strip the magic comma and `ruff format` would do nothing. And if
we'd do `ruff format` first, then it would expand this to multiple lines
and then `ruff check` would do nothing. Given that when you're writing
code you might leave this magic command, knowing that it will expand
later in an expected way, - with COM819 it might if you run linter
first.

So I've added a warning when this rule is enabled and adjusted the
documentation.

I've executed the tests and adjusted the ones that were testing `ALL`.
All tests seems to be fine now, besides that one (seems unrelated to PR)
and bunch of other tests that seems to conflict with my global ruff
settings, I'll report it as an issue separately (see
https://github.com/astral-sh/ruff/issues/25046).
```
Reviewing [1/6] ruff@0.15.12:
Snapshot: semantic_syntax_errors
Source: crates/ruff/tests/cli/lint.rs:3553
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
program: ruff
args:
  - check
  - "--output-format"
  - concise
  - "--preview"
  - "--quiet"
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
-old snapshot
+new results
────────────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
    1     1 │ success: false
    2     2 │ exit_code: 1
    3     3 │ ----- stdout -----
    4     4 │ main.py:1:3: error[invalid-syntax] assignment expression cannot rebind comprehension variable
    5       │-main.py:1:20: error[F821] Undefined name `foo`
    6     5 │ 
    7     6 │ ----- stderr -----
────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

---------

Co-authored-by: Micha Reiser <micha@reiser.io>